name: Lint
on:
 push:
   branches:
     - main
 pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Run Lint checks
        run: |
          ./earthly.sh +lint
