name: Publish

on:
  push:
    tags:
      - v*
    branches:
      - main

concurrency:
  group: ci-publish-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        bundles:
          - calico
          - cert-manager
          - flux
          - coco
          - kubevirt
          - kairos
          - longhorn
          - kyverno
          - metallb
          - multus
          - nginx
          - spinkube
          - system-upgrade-controller
          - argocd
          - "LocalAI"
    env:
      REGISTRY: quay.io
      REGISTRY_USER: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
      - name: Build and push bundle
        uses: docker/build-push-action@v6
        with:
          sbom: false
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: final
          build-args: --BUNDLE=${{ matrix.bundles }}
