name: Test
on:
  pull_request:
  push:
    branches:
      - ci

concurrency:
  group: ci-test-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        bundles:
          - calico
          - cert-manager
          - kubevirt
          - longhorn
          - metallb
          - multus
          - nginx
          - kairos
          - kyverno
          - system-upgrade-controller
          - argocd
          - "LocalAI"
          - flux
          - coco
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - run: ./earthly.sh --ci --push +test --BUNDLE=${{ matrix.bundles }}
